### ISSUE TITLE
Strange error?

### ISSUE THREAD

**Issue by MicMiao** [baabaaox/ScrapyDouban#21]
刚刚发现个问题，没有改过设置。 不知道为什么？🤔️

2022-01-23 01:00:54 [scrapy.core.engine] INFO: Spider opened
2022-01-23 01:00:54 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2022-01-23 01:00:54 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2022-01-23 01:00:56 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://book.douban.com/subject/1041104/ > (referer: None)
2022-01-23 01:00:56 [scrapy.core.scraper] ERROR: Error processing {'douban_id': '1041104', 'slug': 'r6YZ37Q2b'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 858, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/usr/local/lib/python3.9/site-packages/scrapy/utils/defer.py", line 150, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "/srv/ScrapyDouban/scrapy/douban/pipelines.py", line 138, in process_item
    requests = arg_to_iter(self.get_media_requests(item, info))
  File "/srv/ScrapyDouban/scrapy/douban/pipelines.py", line 148, in get_media_requests
    if item["cover"]:
  File "/usr/local/lib/python3.9/site-packages/scrapy/item.py", line 94, in __getitem__
    return self._values[key]
KeyError: 'cover'

🙏

**Comment by baabaaox** [comment]
@MicMiao 

[封面管道](https://github.com/baabaaox/ScrapyDouban/blob/b6d2cced7fc163ede4df560dac1f8dfa218a59b5/scrapy/douban/pipelines.py#L133) 接收到的数据只有  {'douban_id': '1041104', 'slug': 'r6YZ37Q2b'}；BookMetaSpider 里面 parse 方法没有从结果里面解析到任何其它数据，但是日志显示Crawled (200)，你在 parse 函数里面打印一下 response.body 看看服务器返回给你的是什么内容。

**Comment by MicMiao** [comment]
这个error有点奇怪。 没有做任何改变，等了几个小时重新执行 scrapy crawl book_meta， 问题消失了。 今天又再一次出现问题，不过是在爬取的过程当中出现。一共100个id， 成功爬了82个，18个显示了这个问题。目前还在研究。 在封面管道里的 requests = arg_to_iter(self.get_media_requests(item, info)) 下面， 加了一行print(requests.body), 但是打印不出任何东西。

**Comment by baabaaox** [comment]
@MicMiao 不是封面管道里面，是在 BookMetaSpider 的 parse 函数里面打印 response.body，没解析到东西应该是网页返回的内容有问题，你看看到底返回的是什么内容

**Comment by MicMiao** [comment]
Ok, 好的。 最后两次爬取都没有问题。 Thanks a lot again!!

**Comment by TracyWang16** [comment]
> @MicMiao 不是封面管道里面，是在 BookMetaSpider 的 parse 函数里面打印 response.body，没解析到东西应该是网页返回的内容有问题，你看看到底返回的是什么内容

@baabaaox 
抱歉麻烦您！
1. 我在爬取的时候遇到了同样的问题（只改过代理ip设置，未改动其他代码），打印看了一下 response.body为：

```python

2022-02-09 14:25:54 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://book.douban.com/subject/1006646/> (referer: None)
b'<script>var d=[navigator.platform,navigator.userAgent,navigator.vendor].join("|");window.location.href="https://sec.douban.com/a?c=9dcacd&d="+d+"&r=https%3A%2F%2Fbook.douban.com%2Fsubject%2F1006646%2F&k=i41V5kOLu3rhWgRdrhrAX0fFf83qqkil69WspPKH4gY";</script>\n'

```

报错信息为：
```python
2022-02-09 14:25:54 [scrapy.core.scraper] ERROR: Error processing {'douban_id': '1006646', 'slug': '7mjNmzjjb'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 858, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/usr/local/lib/python3.9/site-packages/scrapy/utils/defer.py", line 150, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "/srv/ScrapyDouban/scrapy/douban/pipelines.py", line 138, in process_item
    requests = arg_to_iter(self.get_media_requests(item, info))
  File "/srv/ScrapyDouban/scrapy/douban/pipelines.py", line 148, in get_media_requests
    if item["cover"]:
  File "/usr/local/lib/python3.9/site-packages/scrapy/item.py", line 94, in __getitem__
    return self._values[key]
KeyError: 'cover'

```

2. 同时在爬书籍Subject ID的时候，所有的书籍均返回"Redirecting (301)"

```python
2022-02-09 14:29:13 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (301) to <GET https://book.douban.com/subject/1437446/> from <GET http://book.douban.com/subject/1437446/>
```
或

```python
2022-02-09 14:29:34 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://book.douban.com/subject/1267590/> (referer: None)
```
好像都没有成功爬到ID信息…
想请教一下您，这两个问题可能是因为什么造成的呢？

**Comment by MicMiao** [comment]
Hi, 我估计应该是豆瓣的反爬系统。 如果你等12/24小时后，再试一下，应该不会再出现这个问题。
我每次一般只爬100个id， 如果保险一点的话， 70-80应该就更没有问题了。总的来说， 问题出现后24小时，再试，应该OK了。

**Comment by TracyWang16** [comment]
> 

非常感谢您的回复！我等了24h之后试了一下，可以爬取了，确实是反爬系统的问题。
由于要爬的数据数目较多，最后用代理ip解决了这个问题。再次感谢您的回复！
